document.writeln("<header>");
document.writeln("		<div class=\'header_top\'>");
document.writeln("			<div class=\'header_top_link\'>");
document.writeln("				<div class=\'header_top_link_left\'>");
document.writeln("					<span>");
document.writeln("						<iframe width=\'400\' scrolling=\'no\' height=\'16\' frameborder=\'0\' allowtransparency=\'true\' ");
document.writeln("						src=\'//i.tianqi.com/index.php?c=code&id=11&color=%23FFFFFF&icon=2&site=14\'></iframe>");
document.writeln("					</span>");
document.writeln("				</div>");
document.writeln("				<div class=\'header_top_link_right\'>");
document.writeln("					<a href=\'login.html\'>用户登录</a><span>|</span>");
document.writeln("					<a href=\'register.html\'>新用户注册</a>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("		<div class=\'header_bottom\'>");
document.writeln("			<div class=\'header_bottom_link\'>");
document.writeln("				<div class=\'header_bottom_link_left\'>");
document.writeln("					<a href=\'index.html\'><img src=\'img/logo001.png\' /></a>");
document.writeln("				</div>");
document.writeln("				<div class=\'header_bottom_link_right\'>");
document.writeln("					<div class=\'daohan\'>");
document.writeln("						<ul>");
document.writeln("							<li>");
document.writeln("								<a href=\'index.html\' class=\'bengye\'>首页</a>");
document.writeln("							</li>");
document.writeln("							<li>");
document.writeln("								<a href=\'pages/chuangyexiezhu.html\'>创业协助</a>");
document.writeln("							</li>");
document.writeln("							<li>");
document.writeln("								<a href=\'pages/jiuyexiezhu.html\'>就业协助</a>");
document.writeln("							</li>");
document.writeln("							<li>");
document.writeln("								<a href=\'pages/chuangaifuwu.html\'>创爱服务</a>");
document.writeln("							</li>");
document.writeln("							<li>");
document.writeln("								<a href=\'pages/lizhicanyou.html\'>励志残友</a>");
document.writeln("							</li>");
document.writeln("							<li>");
document.writeln("								<a href=\'pages/aixinqiye.html\'>爱心企业</a>");
document.writeln("							</li>");
document.writeln("							<li>");
document.writeln("								<a href=\'pages/chuangaigongyi.html\'>创爱公益</a>");
document.writeln("							</li>");
document.writeln("							<li>");
document.writeln("								<a href=\'pages/canyouhuodong.html\'>残友活动</a>");
document.writeln("							</li>");
document.writeln("							<li>");
document.writeln("								<a href=\'pages/xiuxianzhibo.html\'>休闲直播</a>");
document.writeln("							</li>");
document.writeln("							<li>");
document.writeln("								<a href=\'pages/ganenqiang.html\'>感恩墙</a>");
document.writeln("							</li>");
document.writeln("						</ul>");
document.writeln("					</div>");
document.writeln("					<div class=\'header_bottom_link_right_bottom\'>");
document.writeln("						<div class=\'erweima\'>");
document.writeln("							<img src=\'img/icon003.png\' />");
document.writeln("							<div class=\'erweima_wz\'>");
document.writeln("								<p>残友飘飘过</p>");
document.writeln("								<p>微信公众号</p>");
document.writeln("								<div class=\'erweima_yc\'>");
document.writeln("									<img src=\'img/img015.jpg\' />");
document.writeln("									<p>微信扫一扫</p>");
document.writeln("								</div>");
document.writeln("							</div>");
document.writeln("						</div>");
document.writeln("						<div class=\'sousuo\'>");
document.writeln("							<input type=\'text\' name=\'\' id=\'\' value=\'\' placeholder=\'请输入需要搜索的内容\' />");
document.writeln("							<img src=\'img/icon002.png\' />");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("	</header>");